---------------------------------------- SHOW ----------------------------------------
ContextualAggregateError: One or more errors in the execution result.
    at handleOutput (/some/path/to/handleOutput.ts:60:19)
    at run (/some/path/to/client.ts:262:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async executeRootType (/some/path/to/client.ts:185:12)
    at async executeRootTypeField (/some/path/to/client.ts:216:20)
    at async <anonymous> (/some/path/to/output|output_return-error_return-error-execution__return-error-execution.ts:26:16) {
  context: {},
  cause: undefined,
  errors: [
    GraphQLError: [
      {
        "code": "too_small",
        "minimum": 1,
        "type": "string",
        "inclusive": true,
        "exact": false,
        "message": "Pokemon name cannot be empty.",
        "path": [
          "name"
        ]
      }
    ]
        at <anonymous> (/some/path/to/graphqlHTTP.ts:32:47)
        at Array.map (<anonymous>)
        at parseExecutionResult (/some/path/to/graphqlHTTP.ts:31:28)
        at Object.unpack (/some/path/to/core.ts:308:26)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async runHook (/some/path/to/runHook.ts:264:16) {
      path: [ 'addPokemon' ],
      locations: undefined,
      extensions: [Object: null prototype] {}
    }
  ]
}
---------------------------------------- SHOW ----------------------------------------
ContextualError: There was an error in the extension "anonymous" (use named functions to improve this error message) while running hook "encode".
    at runPipeline (/some/path/to/runPipeline.ts:76:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.run (/some/path/to/main.ts:286:22)
    at async run (/some/path/to/client.ts:256:20)
    at async executeRootType (/some/path/to/client.ts:185:12)
    at async executeRootTypeField (/some/path/to/client.ts:216:20)
    at async <anonymous> (/some/path/to/output|output_return-error_return-error-execution__return-error-execution.ts:35:3) {
  context: {
    hookName: 'encode',
    source: 'extension',
    extensionName: 'anonymous'
  },
  cause: Error: Something went wrong.
      at <anonymous> (/some/path/to/output|output_return-error_return-error-execution__return-error-execution.ts:37:13)
      at applyBody (/some/path/to/main.ts:310:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
}