/some/path/to/runPipeline.ts:XX:XX
          return new ContextualError(message, {
                 ^
ContextualError: There was an error in the interceptor "anonymous" (use named functions to improve this error message) while running hook "encode".
    at runPipeline (/some/path/to/runPipeline.ts:XX:XX:XX)
    at async <anonymous> (/some/path/to/runner.ts:XX:XX:XX)
    at async Module.run (/some/path/to/run.ts:XX:XX:XX)
    at async sendRequest (/some/path/to/send.ts:XX:XX:XX)
    at async executeRootField (/some/path/to/requestMethods.ts:XX:XX:XX)
    at async <anonymous> (/some/path/to/output_envelope_envelope_error-throw__envelope-error-throw.ts:XX:XX:XX) {
  context: {
    hookName: 'encode',
    source: 'extension',
    interceptorName: 'anonymous'
  },
  cause: Error: Something went wrong.
      at <anonymous> (/some/path/to/output_envelope_envelope_error-throw__envelope-error-throw.ts:XX:XX:XX)
      at applyBody (/some/path/to/runner.ts:XX:XX:XX)
}

Node.js vXX.XX.XX